### ISSUE TITLE
Doesn't work with latest version of material-ui (v3.x)

### ISSUE THREAD

**Issue by RadomirPerisic** [TeamWertarbyte/material-ui-feature-discovery-prompt#2]
I'm getting an error `Uncaught Error: Cannot find module "material-ui/Typography"`.

Per https://material-ui.com/api/typography/ documentation for latest version imports are a bit different, instead of:
```
import { Typography } from 'material-ui'
```
should be:
```
import Typography from '@material-ui/core/Typography';
```

I'm not sure you can make it backwards compatible.

**Comment by saschb2b** [comment]
This component needs an update for sure. Last time we used it, mui was in 1.0 beta. Will refresh it on the weekend to support the latest version. PR is also welcome :D

**Comment by RadomirPerisic** [comment]
I'll try to make a PR this week

**Comment by RadomirPerisic** [comment]
Check out the PR: https://github.com/TeamWertarbyte/material-ui-feature-discovery-prompt/pull/3

**Comment by RadomirPerisic** [comment]
I suggest bumping to 2.0 since these are breaking changes.

**Comment by RadomirPerisic** [comment]
@saschb2b Hey guys, do you plan to release new version on npm?

**Comment by 0x5e5e** [comment]
@saschb2b Could you release a new version?   Current version on npm doesn't include the PR that fixes this.   Thanks!!
